package com.rule;

import com.ashokit.binding.EDRequestBody;
import com.ashokit.binding.EDResponseBody;
import java.util.Date;

global EDResponseBody response;

rule "RIW Rule 1"

	when 
		eDRequestBody: EDRequestBody(isGraduate==true)
	then
		response.setPlanStatus("AP");
		response.setStartDate(new Date());
		response.setEndDate(new Date());
		response.setBenefitAmt(300.0);
	end
	
	rule "RIW Rule 2"
	
	when 
		eDRequestBody: EDRequestBody(isGraduate==false)
	then
		response.setPlanStatus("DN");
		response.setDenialReason("Under Graduate");
	end